version: "3"

services:
  db:
    image: postgres
    build:
      context: .
      dockerfile: Dockerfile_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: gunicorn sabia.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data: